sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - pip install 'lander>=0.1.0,<0.2'
  - pip install pyyaml    # for db2authors.py
script:
  # Pre-build authors.tex using the Travis CI Python
  - make authors.tex
  # Compile PDF using containerized lsst-texmf
  - docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh
    -c 'make'
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - lander --upload --pdf PSTN-018.pdf --lsstdoc PSTN-018.tex --env=travis --ltd-product
    pstn-018
env:
  global:
    -
      # LTD_AWS_ID
      secure: xTh7jjlJJzTtYx+NqBJnX8VK4A4X14JT8QkOPaifi7N+swbMsRM0O/JZdHTXvnkPLwZ/TJscD7GD4ppwaCxWBJktEseVl+yynCLjPiTJ/FMiyosM4sMU57vYFQQvqjHBUyJTOW8Qpibu/1mFhooUlGUQGa2kM/7xdAWqTbMJcKf+J+cTOPeNThl9EJAbN1tZhYkKiTzNxBwwhPg/136KcyAJOGk2InStn9FzWmKOGpXWzpo8pykmJsCD0OtJ4F1x2H5eEd/sfNaft7/CwWi2Q9X6Z8Mdv3FRXXoSAklWkGqg7vSxj6M/f+oC6Hwc/PPUOoCXRbAai2KheLB8AJP/TBXwWUJ4MUYjOVeQAs+MvtpJnkPcaB+qXYrPdXdV5u0dzuxKxNsD9p4rcCCvsyZYeK6IeaFOPSwkVA5e23+kxy63zHiMP2doDUJLp73cgA5EmhGJKEtFA5R5ISmSnGsUUjx6Gda1OwifNUNZ20OyqQ2aabgSsmXuJ7yh1YmLjt3gPzlhNxxWyelB99aSw6LHhue2J3Efd9kcscp7JvY9TDV+fB2PM8b2BuWzRqEVmLLX5X7vi+Gctxzhr+A6XnKuiMcAOM4BSb8kiT9gkEYPWoOkoUKcOYRTApOnvo6oX38yMts0wk1fbuYISNfCqFS1h16XgEV+HCNs45d6FWckhVw=
    -
      # LTD_AWS_SECRET
      secure: ltD4sxDr4w4s5/dE9T/Ppexr+915h6sawSUXrZLSJMC1EkG/Ra/D9G1xtRxM1TxExORlG1gqTiQUVJlFtwMF97my73LrV2TiqFf3MqOka+r5MXWT1m3KY1x7eCdxwZM8VEJzwN2nIBsZMvwOvyixe4zjx8Be7Kq1uN3ZCxd4wJzPA+tbyEnCDnpUM5hjrUVrv7Ax4sJN9XADJTzszNIoo2gRNiT6G/ZhUwD1a1tBlE0eLGsiHVFB2xyst+lic6YymukJQQ9rJKz4nW+bmzFIdGdPNCCPWbBPsELTEJNHrkkPT4YEPSFB1G6FMsuxltT2zEjd5txBe80ZsnPagTF5fsuXWTVn2QX2S0Q7Cq4aP7NfLHC71SN9qIYxYgqONSMTut1TntOfiRy8tHTYTlPLnwmah2AtcTKB99CDRFOiXD7u/hkqsDrpRG1m0crd1NvAklih2p5JtoF0hgBoj8OVrQSBl2T3pmvf/y5dBHUsACck3pSHupPTrs1i9LFKU8TcUSqygWvxrxXA5zn1pDqyC1EXLyRzrRqHGFbQLmVsjcA6Kwdlattc2hUVU0dgdziQvQAeVaBWkYmS8Abk5FrCVRuv8QCjE1V3gcWE42gsnvHTFRO7w48EZI6w1ndW2rhcBvzRcWTUA+H450SJqCfCCEosbeJCPNGR+lcxO3GxsQI=
    -
      # LTD_KEEPER_USERNAME
      secure: vHSFLttFmMXIkP0P9tOCauf1Y5dxe9lWesC/q4tPv+PZV0jJWkt2TEIBffJrf5u7EGsZk5I+VnCSilPkvnYH1HjM82AUAXVYeVzaumgr4ENIt1h+j+Yuv6qW1g0/oltdA4VsytaFlCnUasSbC289/5oREHK8ZPzpeOlMF5t1QniG1/SaJYOlUSFABSZEnHp6V1FpVFCBmLfTR8CpIq7IpSQOV1xz+6e2sd7gWmTKkNRfMfXEyI2mujFMeNw8eBvtX1/P9rdgLozoUtDSqd7Vp2HeNHYSoORxau+NPhWO0Wwl5cc/c12kshFyT165+bbpCWSdmnRlC4WC8TDb+WuxWltf9YXukda1RmxdHNTSMy8NFXoDiifgVzuRd92+VFjUde8q33jFrj1EMoxOJpc05zLthfDWgCfgtDc4rnU55g25g9EQjhOx1O/vN3QLxhNOwiVGs2FTnxceXxTTnXmAZ5bblnyw+P3FA4WEY5zxPRVnVkTPpcdiCvdl1682i4wIpSdm1bt2mtUG2ZKxc1taOGFRg7xcwiRrh+4ufNDftYB2zqIlv1ThAfi6YHqo+tO9zxJ1AG2wiFMMQClKV7FCuuBkX0veAw4VP74+QYE/b/Y95IntRMhjfdzEFNyKf3s/ItOyY9iJcHEczEJ+P8ldlbkw2rhSsamWVHSDQPH7GfU=
    -
      # LTD_KEEPER_PASSWORD
      secure: BFTtjI+APVSSsIKh1V+SDkilVx/Pm3JUFr28XipKUZNpMCqnfO71dtfPTeyJHB5eCqwV9GguMC8hUjyQV1u0Kn+W6eB++mWV9tPRmph2qLpLVo/gx/YrXlZ8OG8j5+vsRXhKdXXD/6XCvysRKV5OMCwug1JaOgKZAMiGaJ94ZtQw6JBCQEKBRqjXekNGRXdRT1asalMxQsgD6DhvBe0+Qs6yQi5ZUDTJ+VxC5bnzlQJPHbgBk/RqrqwNh5cCCOHxaP+0UiiUyoidkKA9VBy/vav/mxS6lT0xqx/+2BgFJgbxR8jVi6jte0L5msONF7Z7I5m6XA3ugoK2qQSh5pL+0A0qyVCl9GuezKTFFVL2u74BsBvyYoQWEwRFSwSWy75mvwQdXk8cqjWkWy9JKQDTz/fAcPgPQLWw9qAqbAridlUoiT+nAdBz3XO8ys7FhGVNmm8XVNYKJXGV1rStuyAgjRQjvThcdL0jecytDXvIaJ2200WibGj/mB69VIv1X7ONc1O9xmIwxcN4SbvqgDufcA1qtcM0/sWc4AeIopZxykBRP50Oa1F6TowHGrIbhNcjANLtxRmsfP/L6sbKy3mk4iBxBC/V5fLpvigxy2LQy4ds/v164nLhpTwrCM2IwFY0aD4XWOruTk1KH5gYQytreCkMKlwEq1Ugqiv8Bz9nX6s=
    -
      # LTD_KEEPER_URL
      secure: tn8cCyRzdfYUlI/aGaKHuItDk0wiPGJ91yyws2OJYCAeNZz/GCmtXiW5fnrwu/rBnbnryONA9vItjtMDo/zpYF2S/G1HH5Y9AmjGcCH34Zbr4MshDhC52CUeeyS3CPmnODpEdQ+tDsm3lG47ic4nIRAO7bQEG3MqdVUUsyo0tH+1Tzwn5qcMR1ifuaaV7rt2xhkSiTcrxijmyxDdHuNDHmLZG1XNWXVwO7B/N5EwEynpAXNI2n1TrA9MoItQHbH/7xmrdSnHe2XUUmuzOu1UoRAZi5K6YTsOnFHalm5BhjHWxc6FWW+eQYBEG2/kLa9iXUu59V9kKQR59UwImPp3fYDLubTVIhtBLyIQjSDQhHTixqdc3LOBXzv/gKMB0CLB1FYpwcjZmzkIj/zOntQSwkKjBBWRczOiv6RgSOTy/6SyaiEI/eZkZFjC3ctFrsHshCvBeV0PDppz1WKhni4fF+1twoXZW+n7l2ouSw2CdzXIHXSuY+cctkSy0pgB2udwxbgr3lUFGTMRtBkrixsasdfRmsscQhjaIJSK6TzCOyAiP8j7jdFId8ozcOhGIEqOWyIJZgDbnpBgbewaHREiXph4C1cjDhfTSiJMGyIiynkOYUgdh3Z9DKsS245LKqqbMc4ir0LAQBQeKZG2tR1r3uAbIQJ/7CNrB+WCuuwrZhs=
